--- 
- name: simple Plabook to install the epic net_sync service
  hosts: all
  become: true
  vars: 
    installation_os_user: pi
    installation_os_group: pi
  
  pre_tasks:

    - name: update apt cache with sudo apt-get --allow-releaseinfo-change update 
      command: sudo apt-get --allow-releaseinfo-change update
      changed_when: false 

    - name: Hold raspberrypi-kernel
      dpkg_selections:
        name: raspberrypi-kernel
        selection: hold

    - name: Upgrade the OS (apt-get upgrade)
      apt:
        upgrade: yes

  roles:
    - { role: einfachit.epic.net_sync }
    - { role: einfachit.epic.ssh_tor}
