---
- name: setup epic docker container host
  hosts: all
  become: true
  gather_facts: true
  tasks:

  - name: remove entry from knowhost, to be able to reconnect after resetting
    ansible.builtin.known_hosts:
      path: –/.ssh/known_hosts
      name: "{{ ansible_hostname }}"
      state: absent

  - name: remove entry from knowhost, to be able to reconnect after resetting
    ansible.builtin.known_hosts:
      path: –/.ssh/known_hosts
      name: "{{ hostname }}.local"
      state: absent


  - name: reset machine to plain os by restoring image from a recovery partition
    reboot:
      reboot_command: "/boot/boot_to_recovery restore {{ hostname }}"
      connect_timeout: 5
      reboot_timeout: 3600
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: whoami
