- src: bassinator.localisation
- src: bassinator.nodered
- src: bassinator.mosquitto
- src: bassinator.simplehttp
- src: bassinator.autoarchive
- src: bassinator.usbbackup
- src: bassinator.tigerjython
- src: bassinator.nginx
- src: bassinator.pi_aseba
